### ISSUE TITLE
Including local jar files 

### ISSUE THREAD

**Issue by Israaaaa** [mkristian/jar-dependencies#30]
I'm trying to build and use a gem that is dependent on jar files. I do not wanna publish the jar files, I need them locally only.

in my .gemspec file, I have the following

      # Jar dependencies
      s.requirements << "jar 'org.elasticsearch:elasticsearch', '1.4.0'"
      s.add_runtime_dependency 'jar-dependencies'
How can I include my local jar files? Because not including them gives me the following error, when trying to use the filter in a config file:

      The error reported is: Couldn't find any filter plugin named 'mygem'. 
      Are you sure this i s correct? Trying to load the mygem filter 
      plugin resulted in this e rror: no such file to load -- thejarfilename
Is this an issue with Logstash? Or should I just include the jar files in a specific way in the gemspec file?

**Comment by mkristian** [comment]
I am not understanding completely what you are trying to do.

the jar dependencies inside the gemspec file will look for them on maven central (respecting any ~/.m2/settings.xml) for mirrors etc. IMPORTANT is to set ```s.platform = 'java'``` otherwise the jar depedencies do not work.

not sure what you mean with local jar files. suppose you have them in /usr/local/jars then you just need to ```require '/usr/local/jars/my.jar'```. this assumes you really do not want to pack them into gem.

if I did not hit your point just give me a bit more info - like the complete gemspec and where the local jars are located or so.

**Comment by Israaaaa** [comment]
i do apologize, I was able to fix my problem. I thought it was something up with Logstash, but obviously it wasn't. I just needed to put the jar files in the directory `lib/`

**Comment by mkristian** [comment]
:)

welcome anyways.
